const sampleBooks = [
  // Computer Science & Technology
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    isbn: "978-0262033848",
    description: "A comprehensive guide to algorithms and data structures used in computer science.",
    genre: ["Computer Science", "Algorithms"],
    subjects: ["Computer Science", "Programming", "Data Structures"],
    publisher: "MIT Press",
    publicationYear: 2009,
    edition: "3rd Edition",
    pages: 1312,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/4A90E2/FFFFFF?text=Algorithms"
  },
  {
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    isbn: "978-0132350884",
    description: "Learn how to write clean, maintainable code that other developers will love to work with.",
    genre: ["Computer Science", "Software Engineering"],
    subjects: ["Programming", "Software Development", "Best Practices"],
    publisher: "Prentice Hall",
    publicationYear: 2008,
    edition: "1st Edition",
    pages: 464,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/50C878/FFFFFF?text=Clean+Code"
  },
  {
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    isbn: "978-0201633610",
    description: "The definitive guide to object-oriented design patterns.",
    genre: ["Computer Science", "Software Design"],
    subjects: ["Object-Oriented Programming", "Design Patterns", "Software Architecture"],
    publisher: "Addison-Wesley",
    publicationYear: 1994,
    edition: "1st Edition",
    pages: 416,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/FF6B35/FFFFFF?text=Design+Patterns"
  },
  {
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    isbn: "978-0201616224",
    description: "Your journey to mastery in software development.",
    genre: ["Computer Science", "Software Development"],
    subjects: ["Programming", "Career Development", "Best Practices"],
    publisher: "Addison-Wesley",
    publicationYear: 1999,
    edition: "1st Edition",
    pages: 352,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/9B59B6/FFFFFF?text=Pragmatic+Programmer"
  },
  {
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    isbn: "978-0596517748",
    description: "Learn the good parts of JavaScript and avoid the bad parts.",
    genre: ["Computer Science", "Web Development"],
    subjects: ["JavaScript", "Web Development", "Programming"],
    publisher: "O'Reilly Media",
    publicationYear: 2008,
    edition: "1st Edition",
    pages: 176,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/F7DC6F/000000?text=JavaScript"
  },

  // Mathematics
  {
    title: "Calculus: Early Transcendentals",
    author: "James Stewart",
    isbn: "978-1285741550",
    description: "A comprehensive introduction to calculus with applications.",
    genre: ["Mathematics", "Calculus"],
    subjects: ["Calculus", "Mathematics", "Engineering"],
    publisher: "Cengage Learning",
    publicationYear: 2015,
    edition: "8th Edition",
    pages: 1368,
    totalCopies: 6,
    availableCopies: 6,
    coverImage: "https://via.placeholder.com/300x400/E74C3C/FFFFFF?text=Calculus"
  },
  {
    title: "Linear Algebra and Its Applications",
    author: "Gilbert Strang",
    isbn: "978-0030105678",
    description: "A modern introduction to linear algebra with practical applications.",
    genre: ["Mathematics", "Linear Algebra"],
    subjects: ["Linear Algebra", "Mathematics", "Engineering"],
    publisher: "Brooks Cole",
    publicationYear: 2005,
    edition: "4th Edition",
    pages: 544,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/3498DB/FFFFFF?text=Linear+Algebra"
  },
  {
    title: "Probability and Statistics for Engineering and the Sciences",
    author: "Jay L. Devore",
    isbn: "978-1305251809",
    description: "Comprehensive coverage of probability and statistics for engineering students.",
    genre: ["Mathematics", "Statistics"],
    subjects: ["Probability", "Statistics", "Engineering"],
    publisher: "Cengage Learning",
    publicationYear: 2015,
    edition: "9th Edition",
    pages: 768,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/2ECC71/FFFFFF?text=Statistics"
  },

  // Physics
  {
    title: "University Physics with Modern Physics",
    author: "Hugh D. Young, Roger A. Freedman",
    isbn: "978-0321973610",
    description: "Comprehensive physics textbook covering classical and modern physics.",
    genre: ["Physics", "Science"],
    subjects: ["Physics", "Mechanics", "Electromagnetism", "Modern Physics"],
    publisher: "Pearson",
    publicationYear: 2015,
    edition: "14th Edition",
    pages: 1600,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/8E44AD/FFFFFF?text=Physics"
  },
  {
    title: "Introduction to Quantum Mechanics",
    author: "David J. Griffiths",
    isbn: "978-1107189638",
    description: "A clear and accessible introduction to quantum mechanics.",
    genre: ["Physics", "Quantum Mechanics"],
    subjects: ["Quantum Mechanics", "Physics", "Mathematics"],
    publisher: "Cambridge University Press",
    publicationYear: 2016,
    edition: "3rd Edition",
    pages: 468,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/34495E/FFFFFF?text=Quantum+Mechanics"
  },

  // Chemistry
  {
    title: "Chemistry: The Central Science",
    author: "Theodore L. Brown, H. Eugene LeMay, Bruce E. Bursten",
    isbn: "978-0134414232",
    description: "Comprehensive chemistry textbook for science and engineering students.",
    genre: ["Chemistry", "Science"],
    subjects: ["Chemistry", "General Chemistry", "Science"],
    publisher: "Pearson",
    publicationYear: 2017,
    edition: "14th Edition",
    pages: 1248,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/E67E22/FFFFFF?text=Chemistry"
  },
  {
    title: "Organic Chemistry",
    author: "Paula Yurkanis Bruice",
    isbn: "978-0134042282",
    description: "A comprehensive guide to organic chemistry with clear explanations.",
    genre: ["Chemistry", "Organic Chemistry"],
    subjects: ["Organic Chemistry", "Chemistry", "Biochemistry"],
    publisher: "Pearson",
    publicationYear: 2016,
    edition: "8th Edition",
    pages: 1344,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/27AE60/FFFFFF?text=Organic+Chemistry"
  },

  // Biology
  {
    title: "Campbell Biology",
    author: "Lisa A. Urry, Michael L. Cain, Steven A. Wasserman",
    isbn: "978-0134093413",
    description: "The world's most successful majors biology text and media program.",
    genre: ["Biology", "Science"],
    subjects: ["Biology", "Cell Biology", "Genetics", "Evolution"],
    publisher: "Pearson",
    publicationYear: 2016,
    edition: "11th Edition",
    pages: 1488,
    totalCopies: 6,
    availableCopies: 6,
    coverImage: "https://via.placeholder.com/300x400/16A085/FFFFFF?text=Biology"
  },
  {
    title: "Molecular Biology of the Cell",
    author: "Bruce Alberts, Alexander Johnson, Julian Lewis",
    isbn: "978-0815344322",
    description: "The definitive text in cell biology with comprehensive coverage.",
    genre: ["Biology", "Cell Biology"],
    subjects: ["Cell Biology", "Molecular Biology", "Biochemistry"],
    publisher: "Garland Science",
    publicationYear: 2014,
    edition: "6th Edition",
    pages: 1464,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/2980B9/FFFFFF?text=Cell+Biology"
  },

  // Engineering
  {
    title: "Engineering Mechanics: Statics",
    author: "Russell C. Hibbeler",
    isbn: "978-0133918922",
    description: "Comprehensive coverage of statics with practical engineering applications.",
    genre: ["Engineering", "Mechanics"],
    subjects: ["Statics", "Mechanical Engineering", "Civil Engineering"],
    publisher: "Pearson",
    publicationYear: 2015,
    edition: "14th Edition",
    pages: 704,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/8B4513/FFFFFF?text=Statics"
  },
  {
    title: "Electric Circuits",
    author: "James W. Nilsson, Susan A. Riedel",
    isbn: "978-0133760033",
    description: "Comprehensive coverage of electric circuits with practical applications.",
    genre: ["Engineering", "Electrical Engineering"],
    subjects: ["Electric Circuits", "Electrical Engineering", "Electronics"],
    publisher: "Pearson",
    publicationYear: 2014,
    edition: "10th Edition",
    pages: 816,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/F39C12/FFFFFF?text=Electric+Circuits"
  },

  // Literature & Classics
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0446310789",
    description: "A powerful story of racial injustice and loss of innocence in the American South.",
    genre: ["Fiction", "Classic"],
    subjects: ["American Literature", "Social Justice", "Coming of Age"],
    publisher: "Grand Central Publishing",
    publicationYear: 1960,
    edition: "1st Edition",
    pages: 376,
    totalCopies: 8,
    availableCopies: 8,
    coverImage: "https://via.placeholder.com/300x400/95A5A6/FFFFFF?text=To+Kill+a+Mockingbird"
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "978-0451524935",
    description: "A dystopian novel about totalitarianism and surveillance society.",
    genre: ["Fiction", "Dystopian"],
    subjects: ["Political Fiction", "Dystopian Literature", "Social Commentary"],
    publisher: "Signet",
    publicationYear: 1949,
    edition: "1st Edition",
    pages: 328,
    totalCopies: 6,
    availableCopies: 6,
    coverImage: "https://via.placeholder.com/300x400/2C3E50/FFFFFF?text=1984"
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0743273565",
    description: "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    genre: ["Fiction", "Classic"],
    subjects: ["American Literature", "Roaring Twenties", "Love Story"],
    publisher: "Scribner",
    publicationYear: 1925,
    edition: "1st Edition",
    pages: 180,
    totalCopies: 7,
    availableCopies: 7,
    coverImage: "https://via.placeholder.com/300x400/E74C3C/FFFFFF?text=The+Great+Gatsby"
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0141439518",
    description: "A classic romance novel about the relationship between Elizabeth Bennet and Mr. Darcy.",
    genre: ["Fiction", "Romance", "Classic"],
    subjects: ["British Literature", "Romance", "Social Commentary"],
    publisher: "Penguin Classics",
    publicationYear: 1813,
    edition: "1st Edition",
    pages: 432,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/D35400/FFFFFF?text=Pride+and+Prejudice"
  },

  // Philosophy
  {
    title: "The Republic",
    author: "Plato",
    isbn: "978-0872201361",
    description: "Plato's masterpiece on justice and the ideal society.",
    genre: ["Philosophy", "Classic"],
    subjects: ["Political Philosophy", "Ethics", "Ancient Philosophy"],
    publisher: "Hackett Publishing",
    publicationYear: 380,
    edition: "1st Edition",
    pages: 300,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/7F8C8D/FFFFFF?text=The+Republic"
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "978-0812968255",
    description: "Personal writings of the Roman Emperor on Stoic philosophy.",
    genre: ["Philosophy", "Stoicism"],
    subjects: ["Stoicism", "Ancient Philosophy", "Self-Help"],
    publisher: "Modern Library",
    publicationYear: 180,
    edition: "1st Edition",
    pages: 256,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/34495E/FFFFFF?text=Meditations"
  },

  // History
  {
    title: "A People's History of the United States",
    author: "Howard Zinn",
    isbn: "978-0061965586",
    description: "A history of the United States from the perspective of ordinary people.",
    genre: ["History", "American History"],
    subjects: ["American History", "Social History", "Political History"],
    publisher: "Harper Perennial",
    publicationYear: 1980,
    edition: "1st Edition",
    pages: 768,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/8B0000/FFFFFF?text=People's+History"
  },
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    isbn: "978-0393317558",
    description: "A groundbreaking examination of why human societies developed differently.",
    genre: ["History", "Anthropology"],
    subjects: ["World History", "Anthropology", "Geography"],
    publisher: "W.W. Norton & Company",
    publicationYear: 1997,
    edition: "1st Edition",
    pages: 480,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/8B4513/FFFFFF?text=Guns+Germs+Steel"
  },

  // Psychology
  {
    title: "Psychology",
    author: "David G. Myers",
    isbn: "978-1464108555",
    description: "Comprehensive introduction to psychology with real-world applications.",
    genre: ["Psychology", "Science"],
    subjects: ["Psychology", "Behavioral Science", "Mental Health"],
    publisher: "Worth Publishers",
    publicationYear: 2013,
    edition: "11th Edition",
    pages: 896,
    totalCopies: 6,
    availableCopies: 6,
    coverImage: "https://via.placeholder.com/300x400/9B59B6/FFFFFF?text=Psychology"
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "978-0374533557",
    description: "A groundbreaking tour of the mind's two systems of thinking.",
    genre: ["Psychology", "Behavioral Economics"],
    subjects: ["Cognitive Psychology", "Behavioral Economics", "Decision Making"],
    publisher: "Farrar, Straus and Giroux",
    publicationYear: 2011,
    edition: "1st Edition",
    pages: 499,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/3498DB/FFFFFF?text=Thinking+Fast+Slow"
  },

  // Economics
  {
    title: "Principles of Economics",
    author: "N. Gregory Mankiw",
    isbn: "978-1305585126",
    description: "Comprehensive introduction to economics with real-world applications.",
    genre: ["Economics", "Social Science"],
    subjects: ["Economics", "Microeconomics", "Macroeconomics"],
    publisher: "Cengage Learning",
    publicationYear: 2017,
    edition: "8th Edition",
    pages: 912,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/27AE60/FFFFFF?text=Principles+of+Economics"
  },
  {
    title: "Freakonomics",
    author: "Steven D. Levitt, Stephen J. Dubner",
    isbn: "978-0060731335",
    description: "A rogue economist explores the hidden side of everything.",
    genre: ["Economics", "Popular Science"],
    subjects: ["Economics", "Social Science", "Data Analysis"],
    publisher: "William Morrow",
    publicationYear: 2005,
    edition: "1st Edition",
    pages: 336,
    totalCopies: 7,
    availableCopies: 7,
    coverImage: "https://via.placeholder.com/300x400/E67E22/FFFFFF?text=Freakonomics"
  },

  // Business & Management
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "978-0307887894",
    description: "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
    genre: ["Business", "Entrepreneurship"],
    subjects: ["Startups", "Business Strategy", "Innovation"],
    publisher: "Crown Business",
    publicationYear: 2011,
    edition: "1st Edition",
    pages: 336,
    totalCopies: 6,
    availableCopies: 6,
    coverImage: "https://via.placeholder.com/300x400/2ECC71/FFFFFF?text=Lean+Startup"
  },
  {
    title: "Good to Great",
    author: "Jim Collins",
    isbn: "978-0066620992",
    description: "Why some companies make the leap and others don't.",
    genre: ["Business", "Management"],
    subjects: ["Business Strategy", "Leadership", "Organizational Behavior"],
    publisher: "Harper Business",
    publicationYear: 2001,
    edition: "1st Edition",
    pages: 320,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/34495E/FFFFFF?text=Good+to+Great"
  },

  // Art & Design
  {
    title: "The Design of Everyday Things",
    author: "Don Norman",
    isbn: "978-0465050659",
    description: "The ultimate guide to human-centered design.",
    genre: ["Design", "Psychology"],
    subjects: ["Design", "User Experience", "Human-Computer Interaction"],
    publisher: "Basic Books",
    publicationYear: 2013,
    edition: "Revised Edition",
    pages: 368,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/E74C3C/FFFFFF?text=Design+of+Everyday+Things"
  },
  {
    title: "Interaction Design: Beyond Human-Computer Interaction",
    author: "Helen Sharp, Jennifer Preece, Yvonne Rogers",
    isbn: "978-1119020752",
    description: "Comprehensive guide to interaction design and user experience.",
    genre: ["Design", "Computer Science"],
    subjects: ["Interaction Design", "User Experience", "Human-Computer Interaction"],
    publisher: "Wiley",
    publicationYear: 2015,
    edition: "4th Edition",
    pages: 584,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/9B59B6/FFFFFF?text=Interaction+Design"
  },

  // Medicine & Health
  {
    title: "Gray's Anatomy",
    author: "Henry Gray",
    isbn: "978-0443066849",
    description: "The classic reference book on human anatomy.",
    genre: ["Medicine", "Anatomy"],
    subjects: ["Anatomy", "Medicine", "Biology"],
    publisher: "Churchill Livingstone",
    publicationYear: 1858,
    edition: "41st Edition",
    pages: 1584,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/8B0000/FFFFFF?text=Gray's+Anatomy"
  },
  {
    title: "Harrison's Principles of Internal Medicine",
    author: "Dennis L. Kasper, Anthony S. Fauci",
    isbn: "978-0071802154",
    description: "The most trusted textbook in internal medicine.",
    genre: ["Medicine", "Internal Medicine"],
    subjects: ["Internal Medicine", "Clinical Medicine", "Diagnosis"],
    publisher: "McGraw-Hill Education",
    publicationYear: 2015,
    edition: "19th Edition",
    pages: 2752,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/2C3E50/FFFFFF?text=Harrison's+Principles"
  },

  // Environmental Science
  {
    title: "Environmental Science: Earth as a Living Planet",
    author: "Daniel B. Botkin, Edward A. Keller",
    isbn: "978-1118427323",
    description: "Comprehensive introduction to environmental science.",
    genre: ["Environmental Science", "Science"],
    subjects: ["Environmental Science", "Ecology", "Sustainability"],
    publisher: "Wiley",
    publicationYear: 2013,
    edition: "9th Edition",
    pages: 688,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/27AE60/FFFFFF?text=Environmental+Science"
  },
  {
    title: "Silent Spring",
    author: "Rachel Carson",
    isbn: "978-0618249060",
    description: "The book that launched the environmental movement.",
    genre: ["Environmental Science", "Non-Fiction"],
    subjects: ["Environmental Science", "Conservation", "Pesticides"],
    publisher: "Houghton Mifflin",
    publicationYear: 1962,
    edition: "1st Edition",
    pages: 378,
    totalCopies: 6,
    availableCopies: 6,
    coverImage: "https://via.placeholder.com/300x400/16A085/FFFFFF?text=Silent+Spring"
  },

  // Astronomy
  {
    title: "The Cosmos: Astronomy in the New Millennium",
    author: "Jay M. Pasachoff, Alex Filippenko",
    isbn: "978-1108431385",
    description: "Comprehensive introduction to astronomy and astrophysics.",
    genre: ["Astronomy", "Science"],
    subjects: ["Astronomy", "Astrophysics", "Space Science"],
    publisher: "Cambridge University Press",
    publicationYear: 2018,
    edition: "5th Edition",
    pages: 720,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/2C3E50/FFFFFF?text=The+Cosmos"
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0553380163",
    description: "From the Big Bang to Black Holes.",
    genre: ["Physics", "Astronomy"],
    subjects: ["Cosmology", "Theoretical Physics", "Astronomy"],
    publisher: "Bantam",
    publicationYear: 1988,
    edition: "1st Edition",
    pages: 256,
    totalCopies: 7,
    availableCopies: 7,
    coverImage: "https://via.placeholder.com/300x400/8E44AD/FFFFFF?text=Brief+History+of+Time"
  },

  // Linguistics
  {
    title: "The Language Instinct",
    author: "Steven Pinker",
    isbn: "978-0061336461",
    description: "How the mind creates language.",
    genre: ["Linguistics", "Psychology"],
    subjects: ["Linguistics", "Cognitive Science", "Language Acquisition"],
    publisher: "Harper Perennial",
    publicationYear: 1994,
    edition: "1st Edition",
    pages: 448,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/3498DB/FFFFFF?text=Language+Instinct"
  },
  {
    title: "Syntactic Structures",
    author: "Noam Chomsky",
    isbn: "978-3110218329",
    description: "The foundation of modern linguistics and cognitive science.",
    genre: ["Linguistics", "Cognitive Science"],
    subjects: ["Linguistics", "Syntax", "Cognitive Science"],
    publisher: "Mouton de Gruyter",
    publicationYear: 1957,
    edition: "1st Edition",
    pages: 117,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/7F8C8D/FFFFFF?text=Syntactic+Structures"
  },

  // Political Science
  {
    title: "The Prince",
    author: "Niccolò Machiavelli",
    isbn: "978-0872209190",
    description: "A political treatise on how to acquire and maintain political power.",
    genre: ["Political Science", "Philosophy"],
    subjects: ["Political Science", "Political Philosophy", "Leadership"],
    publisher: "Hackett Publishing",
    publicationYear: 1532,
    edition: "1st Edition",
    pages: 152,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/8B4513/FFFFFF?text=The+Prince"
  },
  {
    title: "Democracy in America",
    author: "Alexis de Tocqueville",
    isbn: "978-0226805360",
    description: "A classic analysis of American democracy and society.",
    genre: ["Political Science", "History"],
    subjects: ["Political Science", "American Democracy", "Social Analysis"],
    publisher: "University of Chicago Press",
    publicationYear: 1835,
    edition: "1st Edition",
    pages: 722,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/2C3E50/FFFFFF?text=Democracy+in+America"
  },

  // Sociology
  {
    title: "The Sociological Imagination",
    author: "C. Wright Mills",
    isbn: "978-0195133738",
    description: "A classic work on the relationship between personal troubles and public issues.",
    genre: ["Sociology", "Social Science"],
    subjects: ["Sociology", "Social Theory", "Social Analysis"],
    publisher: "Oxford University Press",
    publicationYear: 1959,
    edition: "1st Edition",
    pages: 256,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/8B0000/FFFFFF?text=Sociological+Imagination"
  },
  {
    title: "The Presentation of Self in Everyday Life",
    author: "Erving Goffman",
    isbn: "978-0385094020",
    description: "A sociological analysis of how people present themselves in social situations.",
    genre: ["Sociology", "Social Psychology"],
    subjects: ["Sociology", "Social Psychology", "Social Interaction"],
    publisher: "Anchor",
    publicationYear: 1959,
    edition: "1st Edition",
    pages: 272,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/7F8C8D/FFFFFF?text=Presentation+of+Self"
  },

  // Architecture
  {
    title: "A Pattern Language",
    author: "Christopher Alexander, Sara Ishikawa, Murray Silverstein",
    isbn: "978-0195019193",
    description: "A timeless manual of architectural design patterns.",
    genre: ["Architecture", "Design"],
    subjects: ["Architecture", "Urban Planning", "Design Patterns"],
    publisher: "Oxford University Press",
    publicationYear: 1977,
    edition: "1st Edition",
    pages: 1216,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/8B4513/FFFFFF?text=Pattern+Language"
  },
  {
    title: "The Architecture of Happiness",
    author: "Alain de Botton",
    isbn: "978-0679779155",
    description: "A philosophical exploration of how architecture affects our emotions.",
    genre: ["Architecture", "Philosophy"],
    subjects: ["Architecture", "Aesthetics", "Philosophy"],
    publisher: "Vintage",
    publicationYear: 2006,
    edition: "1st Edition",
    pages: 280,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/D35400/FFFFFF?text=Architecture+of+Happiness"
  },

  // Music
  {
    title: "The Rest Is Noise: Listening to the Twentieth Century",
    author: "Alex Ross",
    isbn: "978-0312427719",
    description: "A comprehensive history of twentieth-century classical music.",
    genre: ["Music", "History"],
    subjects: ["Classical Music", "Music History", "Twentieth Century"],
    publisher: "Picador",
    publicationYear: 2007,
    edition: "1st Edition",
    pages: 624,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/9B59B6/FFFFFF?text=Rest+Is+Noise"
  },
  {
    title: "This Is Your Brain on Music",
    author: "Daniel J. Levitin",
    isbn: "978-0452288522",
    description: "The science of a human obsession.",
    genre: ["Music", "Neuroscience"],
    subjects: ["Music", "Neuroscience", "Psychology"],
    publisher: "Plume",
    publicationYear: 2006,
    edition: "1st Edition",
    pages: 322,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/3498DB/FFFFFF?text=Brain+on+Music"
  },

  // Film Studies
  {
    title: "Film Art: An Introduction",
    author: "David Bordwell, Kristin Thompson",
    isbn: "978-0073535104",
    description: "Comprehensive introduction to film analysis and appreciation.",
    genre: ["Film Studies", "Art"],
    subjects: ["Film Studies", "Cinema", "Visual Arts"],
    publisher: "McGraw-Hill Education",
    publicationYear: 2016,
    edition: "11th Edition",
    pages: 544,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/2C3E50/FFFFFF?text=Film+Art"
  },
  {
    title: "Understanding Movies",
    author: "Louis Giannetti",
    isbn: "978-0205856169",
    description: "An introduction to film appreciation and analysis.",
    genre: ["Film Studies", "Art"],
    subjects: ["Film Studies", "Cinema", "Visual Analysis"],
    publisher: "Pearson",
    publicationYear: 2013,
    edition: "13th Edition",
    pages: 576,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://via.placeholder.com/300x400/8B0000/FFFFFF?text=Understanding+Movies"
  },

  // Poetry
  {
    title: "The Norton Anthology of Poetry",
    author: "Margaret Ferguson, Mary Jo Salter, Jon Stallworthy",
    isbn: "978-0393602926",
    description: "The most comprehensive collection of poetry in English.",
    genre: ["Poetry", "Literature"],
    subjects: ["Poetry", "English Literature", "Literary Analysis"],
    publisher: "W.W. Norton & Company",
    publicationYear: 2017,
    edition: "6th Edition",
    pages: 2208,
    totalCopies: 5,
    availableCopies: 5,
    coverImage: "https://via.placeholder.com/300x400/8E44AD/FFFFFF?text=Norton+Anthology+Poetry"
  },
  {
    title: "Leaves of Grass",
    author: "Walt Whitman",
    isbn: "978-0553211165",
    description: "Whitman's masterpiece of American poetry.",
    genre: ["Poetry", "American Literature"],
    subjects: ["Poetry", "American Literature", "Transcendentalism"],
    publisher: "Bantam Classics",
    publicationYear: 1855,
    edition: "1st Edition",
    pages: 464,
    totalCopies: 4,
    availableCopies: 4,
    coverImage: "https://via.placeholder.com/300x400/27AE60/FFFFFF?text=Leaves+of+Grass"
  }
];

module.exports = sampleBooks; 